# Generated by Django 2.0.6 on 2019-05-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('receive_name', models.CharField(max_length=20)),
                ('detail_address', models.CharField(max_length=150)),
                ('zipcode', models.CharField(max_length=20)),
                ('telphone', models.CharField(blank=True, max_length=20, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.IntegerField(max_length=40, primary_key=True, serialize=False)),
                ('bookname', models.CharField(blank=True, max_length=40, null=True)),
                ('author', models.CharField(blank=True, max_length=40, null=True)),
                ('press', models.CharField(blank=True, max_length=40, null=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=40, null=True)),
                ('printing_time', models.DateTimeField(blank=True, null=True)),
                ('impression', models.CharField(blank=True, max_length=40, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=40, null=True)),
                ('pricing', models.CharField(blank=True, max_length=40, null=True)),
                ('words_number', models.CharField(blank=True, max_length=40, null=True)),
                ('page_number', models.CharField(blank=True, max_length=40, null=True)),
                ('format', models.CharField(blank=True, max_length=40, null=True)),
                ('paper', models.CharField(blank=True, max_length=40, null=True)),
                ('packaging', models.CharField(blank=True, max_length=40, null=True)),
                ('dd_pricing', models.CharField(blank=True, max_length=40, null=True)),
                ('editor', models.CharField(blank=True, max_length=40, null=True)),
                ('content', models.CharField(blank=True, max_length=40, null=True)),
                ('author_content', models.CharField(blank=True, max_length=40, null=True)),
                ('directory', models.CharField(blank=True, max_length=40, null=True)),
                ('comment', models.CharField(blank=True, max_length=40, null=True)),
                ('illustration', models.CharField(blank=True, max_length=40, null=True)),
                ('customer_score', models.CharField(blank=True, max_length=20, null=True)),
                ('sales', models.CharField(blank=True, max_length=20, null=True)),
                ('market_status', models.CharField(blank=True, max_length=20, null=True)),
                ('shelves_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='TClassify',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=20, null=True)),
                ('book_counts', models.CharField(blank=True, max_length=20, null=True)),
                ('category_pid', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_classify',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('create_date', models.ForeignKey(blank=True, db_column='create_date', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xmapp.TBook')),
                ('order_addrid', models.ForeignKey(blank=True, db_column='order_addrid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xmapp.TAddress')),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TOrderitem',
            fields=[
                ('shop_id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('shop_num', models.CharField(blank=True, max_length=20, null=True)),
                ('total_price', models.CharField(blank=True, max_length=20, null=True)),
                ('id', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xmapp.TOrder')),
                ('shop_bookid', models.ForeignKey(blank=True, db_column='shop_bookid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xmapp.TBook')),
            ],
            options={
                'db_table': 't_orderitem',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True)),
                ('user_nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('user_password', models.CharField(blank=True, max_length=20, null=True)),
                ('user_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.AddField(
            model_name='torderitem',
            name='user_ordid',
            field=models.ForeignKey(blank=True, db_column='user_ordid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xmapp.TUser'),
        ),
        migrations.AddField(
            model_name='torder',
            name='order_uid',
            field=models.ForeignKey(blank=True, db_column='order_uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xmapp.TUser'),
        ),
        migrations.AddField(
            model_name='tbook',
            name='classif',
            field=models.ForeignKey(blank=True, db_column='classif', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xmapp.TClassify'),
        ),
        migrations.AddField(
            model_name='taddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xmapp.TUser'),
        ),
    ]
