# Generated by Django 2.0.6 on 2019-05-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taddress',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbook',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tclassify',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='torder',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='torderitem',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tuser',
            options={'managed': False},
        ),
    ]
