# Generated by Django 2.0.6 on 2019-05-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmapp', '0002_auto_20190519_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taddress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbook',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tclassify',
            options={},
        ),
        migrations.AlterModelOptions(
            name='torder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='torderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tuser',
            options={},
        ),
    ]
