# Generated by Django 2.0.6 on 2019-05-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmapp', '0003_auto_20190523_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirm_string',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='用户注册码')),
                ('code_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_confirm_string',
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_created=True)),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('has_confirm', models.BooleanField(default=False, verbose_name='是否确认')),
            ],
            options={
                'db_table': 't_mailbox',
            },
        ),
        migrations.RemoveField(
            model_name='torder',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='torderitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='torderitem',
            name='user_ordid',
        ),
        migrations.AddField(
            model_name='torderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xmapp.TOrder'),
        ),
        migrations.AlterField(
            model_name='taddress',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbook',
            name='author_content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tbook',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tbook',
            name='dd_pricing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbook',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tbook',
            name='illustration',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tbook',
            name='pricing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbook',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tclassify',
            name='category_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tclassify',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='torder',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='torder',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='torder',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='torderitem',
            name='shop_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='torderitem',
            name='shop_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='torderitem',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='confirm_string',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xmapp.Mailbox', verbose_name='关联的用户'),
        ),
    ]
