# Generated by Django 2.0.6 on 2019-05-23 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xmapp', '0007_auto_20190523_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torderitem',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='tuser',
            name='user_status',
        ),
        migrations.AddField(
            model_name='tuser',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuser',
            name='has_confirm',
            field=models.BooleanField(default=False, verbose_name='是否确认'),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='user_email',
            field=models.EmailField(default=1, max_length=254, verbose_name='邮箱'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tuser',
            name='user_nickname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='user_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
