# Generated by Django 2.0.6 on 2019-05-23 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='confirm_string',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='用户注册码')),
                ('code_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_confirm_string',
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_created=True)),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('has_confirm', models.BooleanField(default=False, verbose_name='是否确认')),
            ],
            options={
                'db_table': 't_mailbox',
            },
        ),
        migrations.AddField(
            model_name='confirm_string',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailbox_app.Mailbox', verbose_name='关联的用户'),
        ),
    ]
