# Generated by Django 2.0.6 on 2019-05-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
