# Generated by Django 2.0.6 on 2019-05-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_app', '0002_auto_20190523_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailbox',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='mailbox',
            old_name='username',
            new_name='user_nickname',
        ),
        migrations.RenameField(
            model_name='mailbox',
            old_name='password',
            new_name='user_password',
        ),
    ]
