# Generated by Django 2.0.6 on 2019-05-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_app', '0003_auto_20190523_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm_string',
            name='user',
        ),
        migrations.DeleteModel(
            name='confirm_string',
        ),
        migrations.DeleteModel(
            name='Mailbox',
        ),
    ]
